### ISSUE TITLE
check_mysql* plugins missing

### ISSUE THREAD

**Issue by qeepcologne** [guessi/docker-nagios4#5]
Hi there and thank you for the image which is smaller and more up-to-date then the popular JasonRivers/Docker-Nagios.

The plugins check_mysql and check_mysql_query are missing.
I checked and they are in the source download. I think they are not compiled because of missing dependencies: libmysqlclient-dev and maybe more.

**Comment by guessi** [comment]
@qeepcologne nice catch 👍 

`check_mysql` & `check_mysql_query` not built because of mismatch dependency, reference:
[1]: https://github.com/nagios-plugins/nagios-plugins/blob/release-2.3.3/configure.ac#L378-L391
[2]: https://github.com/nagios-plugins/nagios-plugins/blob/release-2.3.3/REQUIREMENTS#L37-L42

will include them into default dependency once tests passed.

**Comment by guessi** [comment]
@qeepcologne `check_mysql`, `check_mysql_query` should not works, please try to pull the image again.

**Comment by qeepcologne** [comment]
works pretty well, thanks a lot.
